#!/usr/bin/env python3
"""Where IBM Bob reads rules, agents, hooks and modes from, and what is already there.

  rule_locations.py [--workspace DIR]

Read-only; standard library only. Folders and precedence reverse-engineered from bob-code 2.2.0,
build 1.126.0+bob2.2.0.20260924155054 — docs/bob-2.1.0-to-2.2.0.md section 2 and the project_rules
section of skills/bob-agent-rules/reference/injected-rules.md, both re-verified on that build.

Each rule root (workspace `.bob/` and global `~/.bob/`) also reads every directory (or symlink)
under its sibling `plugins/` folder, sorted by name, for the same `rules-<mode>/` and `rules/`
subdirectories. Precedence is kind-first, root-second: `rules-<mode>` (base then plugins,
alphabetically) outranks `rules` (base then plugins, alphabetically) outranks `AGENTS.md`, and the
whole workspace side outranks the whole global side. See the "precedence" line this script prints.

Trust: bob-code 2.2.0 takes `workspace.isTrusted` from the IDE at runtime and does not consult
`trustedFolders.json` any more (that store existed on 2.1.0 but its lookup function was already
dead code there). This script cannot read the IDE's runtime trust state offline, so it does not
claim to know whether a folder is trusted; a leftover `trustedFolders.json` is shown only as
historical 2.1.0 information, clearly labelled, never as the current trust status.
"""
import argparse
import glob
import json
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _bobcheck  # noqa: E402

HOME = os.path.expanduser("~")
SKIP = {".DS_Store", "Thumbs.db", ".gitkeep", ".gitignore", ".bobignore"}


def files_under(d, depth=5):
    out = []
    if os.path.isdir(d):
        base = d.rstrip(os.sep).count(os.sep)
        for root, dirs, files in os.walk(d):
            if root.count(os.sep) - base >= depth:
                dirs[:] = []
            out += [os.path.join(root, f) for f in sorted(files) if f not in SKIP]
    return out


def plugin_names(root):
    """Plugin directory (or symlink) names under root/plugins, sorted alphabetically."""
    d = os.path.join(root, "plugins")
    try:
        return sorted(n for n in os.listdir(d)
                       if os.path.isdir(os.path.join(d, n)) or os.path.islink(os.path.join(d, n)))
    except OSError:
        return []


def rule_dirs(root):
    """Rule directories under one root (.bob or ~/.bob), in bob-code 2.2.0 precedence order:
    base rules-<mode>/, then each plugin's rules-<mode>/ (alphabetical), then base rules/, then
    each plugin's rules/ (alphabetical)."""
    plugins = plugin_names(root)
    dirs = sorted(glob.glob(os.path.join(root, "rules-*")))
    for name in plugins:
        dirs += sorted(glob.glob(os.path.join(root, "plugins", name, "rules-*")))
    dirs.append(os.path.join(root, "rules"))
    for name in plugins:
        dirs.append(os.path.join(root, "plugins", name, "rules"))
    return dirs


def hooks_in(path):
    try:
        with open(path, encoding="utf-8") as f:
            hooks = json.load(f).get("hooks") or {}
    except Exception:
        return []
    return [f"{ev} {g.get('matcher') or '*'} → {h.get('command')}" for ev, groups in hooks.items()
            for g in groups for h in g.get("hooks", [])]


def scope(label, root, base, ws=None):
    rel = lambda p: os.path.relpath(p, base)  # noqa: E731
    lines = []
    for d in rule_dirs(root):
        for p in files_under(d):
            flag = "   ! generated by /init, review" if p.endswith("AGENTS.md") and "rules-" in d else ""
            lines.append(f"{rel(p)}  {os.path.getsize(p)} B{flag}")
    if ws and os.path.isfile(os.path.join(ws, "AGENTS.md")):
        lines.append(f"AGENTS.md  {os.path.getsize(os.path.join(ws, 'AGENTS.md'))} B")
    lines += [f"{rel(p)}  {os.path.getsize(p)} B" for p in files_under(os.path.join(root, "agents"), 1)]
    lines += [rel(p) for p in files_under(os.path.join(root, "skills")) if p.endswith("SKILL.md")]
    if os.path.isfile(os.path.join(root, "custom_modes.yaml")):
        lines.append(rel(os.path.join(root, "custom_modes.yaml")))
    settings = os.path.join(root, "settings.json") if ws else os.path.join(root, "settings", "settings.json")
    lines += [f"hook {h}" for h in hooks_in(settings)]
    print(f"{label:<11} {base}")
    for l in lines or ["(nothing)"]:
        print(f"  {l}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--workspace", default=os.getcwd(), help="workspace root to inspect (default: cwd)")
    _bobcheck.add_arguments(ap)
    a = ap.parse_args()
    _bobcheck.check("rule_locations", quiet=a.no_version_check, strict=a.strict)
    ws = os.path.abspath(a.workspace)
    print("precedence  .bob/rules-<mode>/ > .bob/plugins/<name>/rules-<mode>/ (alpha) > .bob/rules/ > "
          ".bob/plugins/<name>/rules/ (alpha) > AGENTS.md > ~/.bob/rules-<mode>/ > "
          "~/.bob/plugins/<name>/rules-<mode>/ (alpha) > ~/.bob/rules/ > ~/.bob/plugins/<name>/rules/ (alpha)")
    scope("workspace", os.path.join(ws, ".bob"), ws, ws)
    try:
        if subprocess.run(["git", "-C", ws, "check-ignore", "-q", ".bob/rules/x.md"], capture_output=True).returncode != 0 \
                and subprocess.run(["git", "-C", ws, "rev-parse"], capture_output=True).returncode == 0:
            print("  ! .bob/ is not git-ignored")
    except Exception:
        pass
    scope("global", os.path.join(HOME, ".bob"), HOME)
    print("trust       bob-code 2.2.0 takes workspace.isTrusted from the IDE at runtime; this script "
          "cannot read that state offline and does not know whether this folder is trusted.")
    legacy = os.path.join(HOME, ".bob", "trustedFolders.json")
    if os.path.isfile(legacy):
        try:
            with open(legacy, encoding="utf-8") as f:
                folders = json.load(f).get("folders", {})
            status = folders.get(ws) or next((v for k, v in folders.items() if ws.startswith(k.rstrip("/") + "/")), None)
            if status is not None:
                print(f"trust (2.1.0 leftover)  trustedFolders.json still lists this folder as {status!r}; "
                      "bob-code 2.2.0 does not read this file, shown only as historical 2.1.0 info")
        except Exception:
            pass


if __name__ == "__main__":
    main()
