#!/usr/bin/env python3
"""Where IBM Bob reads rules, agents, hooks and modes from, and what is already there.

  rule_locations.py [--workspace DIR]

Read-only; standard library only. Folders and precedence reverse-engineered from bob-code 2.1.0.
"""
import argparse
import glob
import json
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _bobcheck  # noqa: E402

HOME = os.path.expanduser("~")
SKIP = {".DS_Store", "Thumbs.db", ".gitkeep", ".gitignore", ".bobignore"}


def files_under(d, depth=5):
    out = []
    if os.path.isdir(d):
        base = d.rstrip(os.sep).count(os.sep)
        for root, dirs, files in os.walk(d):
            if root.count(os.sep) - base >= depth:
                dirs[:] = []
            out += [os.path.join(root, f) for f in sorted(files) if f not in SKIP]
    return out


def hooks_in(path):
    try:
        with open(path, encoding="utf-8") as f:
            hooks = json.load(f).get("hooks") or {}
    except Exception:
        return []
    return [f"{ev} {g.get('matcher') or '*'} → {h.get('command')}" for ev, groups in hooks.items()
            for g in groups for h in g.get("hooks", [])]


def scope(label, root, base, ws=None):
    rel = lambda p: os.path.relpath(p, base)  # noqa: E731
    lines = []
    for d in sorted(glob.glob(os.path.join(root, "rules-*"))) + [os.path.join(root, "rules")]:
        for p in files_under(d):
            flag = "   ! generated by /init, review" if p.endswith("AGENTS.md") and "rules-" in d else ""
            lines.append(f"{rel(p)}  {os.path.getsize(p)} B{flag}")
    if ws and os.path.isfile(os.path.join(ws, "AGENTS.md")):
        lines.append(f"AGENTS.md  {os.path.getsize(os.path.join(ws, 'AGENTS.md'))} B")
    lines += [f"{rel(p)}  {os.path.getsize(p)} B" for p in files_under(os.path.join(root, "agents"), 1)]
    lines += [rel(p) for p in files_under(os.path.join(root, "skills")) if p.endswith("SKILL.md")]
    if os.path.isfile(os.path.join(root, "custom_modes.yaml")):
        lines.append(rel(os.path.join(root, "custom_modes.yaml")))
    settings = os.path.join(root, "settings.json") if ws else os.path.join(root, "settings", "settings.json")
    lines += [f"hook {h}" for h in hooks_in(settings)]
    print(f"{label:<11} {base}")
    for l in lines or ["(nothing)"]:
        print(f"  {l}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--workspace", default=os.getcwd())
    _bobcheck.add_arguments(ap)
    a = ap.parse_args()
    _bobcheck.check("rule_locations", quiet=a.no_version_check, strict=a.strict)
    ws = os.path.abspath(a.workspace)
    print("precedence  .bob/rules-<mode>/ > .bob/rules/ > AGENTS.md > ~/.bob/rules-<mode>/ > ~/.bob/rules/")
    scope("workspace", os.path.join(ws, ".bob"), ws, ws)
    try:
        if subprocess.run(["git", "-C", ws, "check-ignore", "-q", ".bob/rules/x.md"], capture_output=True).returncode != 0 \
                and subprocess.run(["git", "-C", ws, "rev-parse"], capture_output=True).returncode == 0:
            print("  ! .bob/ is not git-ignored")
    except Exception:
        pass
    scope("global", os.path.join(HOME, ".bob"), HOME)
    trusted = os.path.join(HOME, ".bob", "trustedFolders.json")
    try:
        with open(trusted, encoding="utf-8") as f:
            folders = json.load(f).get("folders", {})
        status = folders.get(ws) or next((v for k, v in folders.items() if ws.startswith(k.rstrip("/") + "/")), None)
        print(f"trust       {status or 'not recorded — rules are not loaded in untrusted folders'}")
    except Exception:
        pass


if __name__ == "__main__":
    main()
